(function () {
    const translations = {
        es: {
            heroTitle: 'IMAGINACIÓN EN GRANDE. PEQUEÑAS AVENTURAS.',
            heroSubtitle: 'Alquiler de juegos temáticos y áreas interactivas para fiestas infantiles en Austin y sus alrededores.',
            heroDescription: 'Transformamos tu celebración en una aventura para jugar, imaginar y descubrir, con juguetes montables temáticos, actividades sensoriales y experiencias interactivas. Entregamos e instalamos profesionalmente cada área de juego en el lugar de tu evento, lista para que los niños exploren, imaginen y disfruten.',
            servicesBtn: 'Ver servicios',
            contactBtn: 'Contáctanos',
            homeBtn: 'Inicio',
            backHome: '← Volver al inicio',
            servicesTitle: 'ÁREAS DE JUEGO TEMÁTICAS PARA FIESTAS INFANTILES',
            servicesDesc: 'Elige un área de juego temática y convierte tu celebración en una aventura para jugar, imaginar y explorar. Llevamos e instalamos profesionalmente cada área en el lugar de tu evento, en Austin y sus alrededores, para que todo esté listo cuando comience la diversión.',
            ranchCardTitle: 'ÁREA DE JUEGO TEXAS RANCH',
            spaceCardTitle: 'ÁREA DE JUEGO SPACE EXPLORERS',
            miniSpaceCardTitle: 'ÁREA SENSORIAL BABY SPACE EXPLORERS',
            cityCardTitle: 'ÁREA DE JUEGO MINI CITY',
            ranchCardButton: 'TRÁELO',
            spaceCardButton: 'TRÁELO',
            miniCardButton: 'TRÁELO',
            cityCardButton: 'TRÁELO',
            bringIt: 'BRING IT TO',
            toMyParty: 'MY PARTY',
            contactBackHome: '← Volver al inicio',
            directoryTab: 'Directorio e historia',
            quoteTab: 'Solicitar cotización',
            contactTitle: 'Planifiquemos su gran día',
            contactIntro: 'Cuéntanos sobre tu celebración y te ayudaremos a elegir el setup perfecto.',
            formFirstName: 'Nombre',
            formLastName: 'Apellido',
            formPhone: 'Número de teléfono',
            formEmail: 'Correo electrónico',
            formZip: 'Código postal del evento',
            formDate: 'Fecha del evento',
            formDateHelp: 'Elige una fecha del calendario.',
            locationLegend: '¿Dónde será la celebración?',
            locationHome: 'Casa privada',
            locationPark: 'Parque',
            locationVenue: 'Lugar / salón',
            setupPrompt: '¿Qué setup te gustaría cotizar?',
            setupDefault: 'Selecciona un setup',
            requestQuote: 'Solicitar cotización',
            successTitle: '¡Solicitud recibida!',
            successLead: 'Gracias, <strong id="successCustomerName">amigo</strong>! Hemos recibido los detalles de tu celebración.',
            successSetup: 'Setup:',
            successDate: 'Fecha:',
            successLocation: 'Ubicación:',
            whatsappBtn: '💬 Escríbenos por WhatsApp',
            sendAnother: 'Enviar otra solicitud',
            directoryBackHome: '← Volver al inicio',
            directoryStoryTitle: '¡Gracias por pasar por aquí! ✨',
            directoryStoryIntro: 'Sabemos que planear una celebración toma tiempo, amor y atención a cada detalle. Estamos muy contentos y agradecidos de que estés aquí explorando nuestro universo lúdico.',
            trustAustin: '📍 Sirviendo a Austin y áreas cercanas',
            trustClean: '🧼 100% limpiado y desinfectado',
            trustSetup: '🚚 Entregado y montado profesionalmente',
            storyMission: 'NUESTRA HISTORIA Y MISIÓN',
            storyHeadline: 'Algunos momentos llevan años soñándose — y solo unas horas viviéndose.',
            storyIntro1: 'Esa idea siempre ha estado en el corazón de Austin Kids Events. Sabemos lo mucho que puede implicar un primer cumpleaños: la anticipación, la planificación, los pequeños detalles y la esperanza de que, cuando llegue el día, se sienta realmente especial.',
            storyIntro2: 'Por eso quisimos crear algo que haga más que llenar un espacio de fiesta. Nuestros setups están diseñados para que los niños realmente jueguen, exploren e imaginen, mientras también se convierten en parte de la celebración, creando fotos hermosas y dando a los padres menos cosas que gestionar.',
            storyIntro3: 'Porque cuando empieza la fiesta, también deberías poder disfrutarla.',
            storyQuote: 'La infancia pasa rápido. Estamos aquí para hacer que algunos momentos valgan la pena recordar.',
            storyTagline: 'Austin Kids Events — impulsado por la imaginación.',
            connectTitle: '¿Cómo te gustaría conectar?',
            connectSubtitle: 'Elige tu canal preferido para respuestas rápidas, preguntas rápidas o para ver nuestras últimas aventuras de fiesta.',
            connectWhatsApp: 'MÉNSAJE POR WHATSAPP',
            connectCall: 'LLÁMANOS',
            connectLinktree: 'LINKTREE',
            connectInstagram: 'SÍGUENOS EN INSTAGRAM',
            connectFacebook: 'PÁGINA DE FACEBOOK',
            connectWhatsAppText: 'Preguntas rápidas y detalles de la fiesta',
            connectCallText: 'Llamadas directas para reservaciones',
            connectLinktreeText: 'Mira todos nuestros enlaces en un solo lugar',
            connectInstagramText: 'Montajes reales, detrás de cámaras y juego en acción.',
            exploreExperiences: 'EXPLORA LAS EXPERIENCIAS',
            worldsTitle: 'Conoce nuestros mundos de juego',
            filterAll: 'Todos los setups',
            filterRanch: 'Texas Ranch',
            filterSpace: 'Space Explorers',
            filterMiniSpace: 'Baby Space Explorers',
            filterCity: 'Mini City',
            worldLead: 'Elige un setup temático pensado para jugar de verdad, imaginar en grande y crear fotos memorables — entregado y montado profesionalmente en tu evento.',
            worldRanchTag: 'TEMA 01',
            worldSpaceTag: 'TEMA 02',
            worldMiniTag: 'TEMA 02B',
            worldCityTag: 'TEMA 03',
            ranchTagline: 'Un pedacito de Texas hecho para grandes imaginaciones.',
            ranchCopy: 'Los vaqueros y vaqueras pequeños pueden montar, recorrer y jugar su camino a través de una aventura de rancho con caballos, tractores, animales de granja y detalles clásicos de Texas.',
            spaceTagline: 'Una misión pensada para pequeños astronautas curiosos.',
            spaceCopy: 'Los rovers, el equipo espacial, los paisajes lunares y las actividades interactivas convierten la celebración en una misión práctica donde los niños pueden explorar, imaginar y jugar más allá de la Tierra.',
            miniTagline: 'Su primera misión comienza en la Luna.',
            miniCopy: 'Baby Space Explorers crea un rincón lunar acolchado donde bebés y niños de hasta 2 años y medio pueden gatear, tocar, moverse y descubrir a su propio ritmo. Los módulos espaciales, los paneles de actividades y el juego sensorial despiertan la curiosidad y convierten cada movimiento en una nueva misión.',
            cityTagline: 'Toda una ciudad pequeña hecha para pequeños conductores.',
            cityCopy: 'Autos a pedal, calles, señales de tráfico y juego imaginativo dan a los niños su propio mundo para conducir, explorar y crear sus propias reglas mientras avanza el juego.',
            ranchFeature1: 'Juegos de rancho',
            ranchFeature2: 'Caballos',
            ranchFeature3: 'Animales de granja',
            ranchFeature4: 'Tractores',
            ranchFeature5: 'Granero',
            spaceFeature1: 'Rovers espaciales',
            spaceFeature2: 'Equipo de astronauta',
            spaceFeature3: 'Mando lunar',
            spaceFeature4: 'Terreno lunar',
            spaceFeature5: 'Juego espacial',
            miniFeature1: 'Superficie lunar acolchada',
            miniFeature2: 'Módulos espaciales',
            miniFeature3: 'Juego sensorial',
            miniFeature4: 'Paneles de actividades',
            miniFeature5: 'Exploración libre',
            cityFeature1: 'Autos a pedal',
            cityFeature2: 'Calles',
            cityFeature3: 'Señales de tráfico',
            cityFeature4: 'Juego de ciudad',
            cityFeature5: 'Pequeños conductores',
            exploreRanch: 'Explorar Texas Ranch',
            exploreSpace: 'Explorar Space Explorers',
            exploreMini: 'Explorar Baby Space Explorers',
            exploreCity: 'Explorar Mini City',
            trustFooterTitle1: 'Atendemos Austin',
            trustFooterText1: 'y áreas cercanas. Entrega y montaje profesional incluidos.',
            trustFooterTitle2: 'Limpio, seguro y revisado',
            trustFooterText2: 'Nuestro equipo se limpia y revisa antes de cada evento.',
            trustFooterTitle3: 'Renta de 12 horas',
            trustFooterText3: 'Hay tiempo de sobra para disfrutar. Normalmente se entrega antes de las 10 AM y se recoge después de las 9 PM.',
            trustFooterTitle4: 'Hecho para recuerdos',
            trustFooterText4: 'Diseñado para jugar de verdad, fotos bonitas y celebraciones sin estrés.',
            viewSetup: 'Explorar setup',
            viewAllSetups: '← Ver todos los setups',
            detailSet: 'Set de juegos',
            detailExperience: 'La experiencia',
            detailMission: 'La misión',
            detailBook: 'Quiero este set',
            detailReserve: 'Reservar esta aventura',
            detailBuild: 'Construyan su ciudad',
            spaceAgeSuffix: 'años',
            miniAgeSuffix: 'años',
            spaceCommandLabel: 'Centro de mando',
            spaceReady: 'LISTOS PARA DESPEGAR',
            spaceSpecWindow: 'Horario de alquiler',
            spaceSpecZone: 'Zona de lanzamiento',
            spaceSignoff: 'Cuando se ponen los cascos, alguien suele empezar a asignar misiones.',
            cityStoryTitle: 'Un pequeño mundo sin equivocación.',
            cityChoiceText: 'Las familias pueden elegir entre distintas configuraciones de Mini City, desde vehículos clásicos a pedal hasta una colección más elegante de autos estilo lujo.',
            cityDeliveryText: 'Cada setup se entrega y se monta completamente antes del evento, y se recoge después. Los alquileres duran hasta 12 horas, y se pueden incluir actividades o entretenimiento adicional dependiendo de la celebración.',
            cityAvailabilityText: 'Disponible para cumpleaños, reuniones familiares y eventos infantiles en todo Austin.',
            cityControlLabel: 'Control de la ciudad',
            cityStatus: 'TODAS LAS RUTAS ABIERTAS',
            citySpecWindow: 'Horario de alquiler',
            citySpecZone: 'Zona de juego',
            citySignoff: 'Y a diferencia del I-35, el tráfico en Mini City es parte de la diversión. 😄',
            miniCommandLabel: 'Centro de mando',
            miniReady: 'LISTOS PARA EXPLORADORES PEQUEÑOS',
            miniSpecWindow: 'Horario de alquiler',
            miniSpecZone: 'Zona de juego',
            miniSpecSignoff: 'Pequeños exploradores, grandes descubrimientos.',
            ranchBack: '← Ver todos los setups',
            ranchKicker: 'ÁREA DE JUEGO TEMÁTICA',
            ranchLead: 'Caballitos montables, tractores infantiles y un minicorral convierten tu celebración en un pequeño rancho creado para jugar, imaginar y explorar.',
            ranchCta: 'Quiero este set',
            ranchInfoTitle: 'EL ÁREA DE JUEGO',
            ranchInfoText: 'Un pequeño rancho para imaginar en grande',
            ranchBodyIntro: '¡A montar! Los niños podrán jugar con caballitos montables, tractores infantiles y un minicorral con vacas, rodeados de césped artificial, cerca blanca y divertidos detalles de rancho. Llevamos e instalamos todo en el lugar de tu evento, listo para que los pequeños rancheros jueguen y exploren.',
            ranchIncludesLabel: 'Incluye',
            ranchIncludesText: 'Caballitos montables, tractores y minicorral',
            ranchIdealLabel: 'Ideal para',
            ranchIdealText: 'Fiestas infantiles',
            ranchThemeLabel: 'Temática',
            ranchThemeText: 'Rancho texano',
            bringIt: 'TRAE EL RANCHO',
            toMyParty: 'A MI FIESTA',
            spaceBack: '← Ver todos los setups',
            spaceKicker: 'ÁREA DE JUEGO TEMÁTICA',
            spaceLead: 'Pequeños astronautas. Grandes misiones.',
            spaceCta: 'Reservar esta misión',
            spaceMissionKicker: 'LA MISIÓN',
            spaceMissionTitle: 'Pequeños astronautas. Grandes misiones.',
            spaceMissionText1: 'Space Explorers está diseñado para niños de 3 a 5 años que quieren conducir, explorar e inventar sus propias aventuras. Los pequeños astronautas pueden recorrer la superficie lunar, reportarse al Centro de Mando Espacial y crear nuevas misiones mientras juegan juntos.',
            spaceMissionText2: '',
            spaceMissionText3: '',
            spaceMissionText4: '',
            spaceSpecAge: 'Edad recomendada',
            spaceSpecWindow: 'Alquiler',
            spaceSpecZone: 'Servicio',
            spaceSpecAvailable: 'Disponible en',
            spaceSpecAgeValue: '3 a 5 años',
            spaceSpecWindowValue: 'Hasta 12 horas',
            spaceSpecZoneValue: 'Entrega, instalación y retiro',
            spaceSpecAvailableValue: 'Austin, Round Rock, Pflugerville, Georgetown, Cedar Park y Leander',
            spaceCommandLabel: 'Centro de mando',
            spaceReady: 'LISTOS PARA DESPEGAR',
            spaceSignoff: 'Pequeños astronautas, grandes misiones.',
            cityBack: '← Ver todos los setups',
            cityKicker: 'ÁREA DE JUEGO TEMÁTICA',
            cityLead: 'Toda una ciudad para jugar al volante.',
            cityCta: 'TRAE MINI CITY',
            toMyParty: 'A MI FIESTA →',
            cityInfoTitle: 'Mini City',
            cityInfoText: 'Mini City convierte el espacio de la fiesta en una ciudad interactiva con carritos montables, calles y señales de tránsito. Los niños pueden conducir, explorar e inventar sus propias aventuras mientras desarrollan la coordinación, la orientación espacial y ponen en marcha la imaginación. El colorido montaje también se integra a la decoración y se convierte en un fondo natural para las fotos.',
            miniBack: '← Ver todos los setups',
            miniKicker: 'ÁREA DE JUEGO SENSORIAL · 0 A 2½ AÑOS',
            miniLead: 'Una aventura lunar pequeña, diseñada para nuestras exploradoras y exploradores más pequeños — bebés y toddlers hasta 2½ años.',
            miniCta: 'Reservar esta aventura',
            miniMissionKicker: 'LA MISIÓN',
            miniMissionTitle: 'La primera misión comienza en la Luna.',
            miniMissionText1: 'Baby Space Explorers convierte la celebración en un rincón lunar acolchado para bebés y niños de hasta 2 años y medio. Allí pueden gatear, moverse, tocar y descubrir a su propio ritmo.',
            miniMissionText2: 'Los módulos espaciales, los paneles de actividades y los elementos sensoriales los invitan a seguir su curiosidad y encontrar algo nuevo con cada movimiento. Llevamos, instalamos y retiramos el área completa para que todo esté listo antes de que comience la misión.',
            miniSpecAge: 'Rango de edad',
            miniSpecWindow: 'Horario de alquiler',
            miniSpecZone: 'Zona de juego',
            miniSpecUpTo: 'Hasta 2½ años',
            miniSpecHours: 'Hasta 12 horas',
            miniSpecAustin: 'Austin',
            miniSpecSignoff: 'Pequeños exploradores, grandes descubrimientos.',
            miniBringIt: 'TRAE LA LUNA A MI FIESTA →',
            miniToMyParty: 'MI FIESTA →'
        },
        en: {
            heroTitle: 'BIG IMAGINATIONS. LITTLE ADVENTURES.',
            heroSubtitle: 'Themed kids party rentals and interactive play setups in Greater Austin.',
            heroDescription: 'We bring imaginative play to your celebration with themed ride-ons, sensory activities and interactive experiences — delivered and professionally set up at your party venue.',
            servicesBtn: 'View services',
            contactBtn: 'Contact us',
            homeBtn: 'Home',
            backHome: '← Back to home',
            servicesTitle: 'THEMED RIDE-ON RENTALS FOR KIDS',
            servicesDesc: 'Choose a complete themed play setup and turn your celebration into a hands-on adventure. We deliver and professionally set up every play area at venues across Greater Austin, ready for kids to explore and enjoy.',
            ranchCardTitle: 'TEXAS RANCH THEMED PLAY SETUP',
            spaceCardTitle: 'SPACE EXPLORERS THEMED PLAY SETUP',
            miniSpaceCardTitle: 'BABY SPACE EXPLORERS',
            cityCardTitle: 'MINI CITY THEMED PLAY SETUP',
            ranchCardButton: 'BRING IT TO',
            spaceCardButton: 'BRING IT TO',
            miniCardButton: 'BRING IT TO',
            cityCardButton: 'BRING IT TO',
            bringIt: 'BRING IT TO',
            toMyParty: 'MY PARTY',
            contactBackHome: '← Back to home',
            directoryTab: 'Directory & Story',
            quoteTab: 'Request a Quote',
            contactTitle: 'Let’s plan their big day',
            contactIntro: 'Tell us about your celebration and we’ll help you choose the perfect setup.',
            formFirstName: 'First name',
            formLastName: 'Last name',
            formPhone: 'Phone number',
            formEmail: 'Email address',
            formZip: 'Event ZIP code',
            formDate: 'Event date',
            formDateHelp: 'Choose a date from the calendar.',
            locationLegend: 'Where will the celebration take place?',
            locationHome: 'Private home',
            locationPark: 'Park',
            locationVenue: 'Venue / Hall',
            setupPrompt: 'Which setup would you like a quote for?',
            setupDefault: 'Select a setup',
            requestQuote: 'Request a quote',
            successTitle: 'Request Received!',
            successLead: 'Thank you, <strong id="successCustomerName">there</strong>! We’ve received your celebration details.',
            successSetup: 'Setup:',
            successDate: 'Date:',
            successLocation: 'Location:',
            whatsappBtn: '💬 Message us on WhatsApp',
            sendAnother: 'Send another request',
            directoryBackHome: '← Back to home',
            directoryStoryTitle: 'Thank you for stopping by! ✨',
            directoryStoryIntro: 'We know planning a celebration takes time, love, and attention to every detail. We are so happy and grateful you are here exploring our playful universe!',
            trustAustin: '📍 Serving Greater Austin & Surrounding Areas',
            trustClean: '🧼 100% Cleaned & Sanitized',
            trustSetup: '🚚 Delivered & Professionally Setup',
            storyMission: 'OUR STORY & MISSION',
            storyHeadline: 'Some moments take years to dream about — and only a few hours to live.',
            storyIntro1: 'That idea has always been at the heart of Austin Kids Events. We know how much can go into those first birthdays: the anticipation, the planning, the little details, and the hope that when the day finally comes, it feels truly special.',
            storyIntro2: 'So we wanted to create something that does more than fill a party space. Our setups are made for kids to actually play, explore and imagine — while also becoming part of the celebration itself, creating beautiful photos and giving parents fewer things to manage.',
            storyIntro3: 'Because when the party starts, you should be able to enjoy it too.',
            storyQuote: 'Childhood goes by fast. We’re here to make some of it worth remembering.',
            storyTagline: 'Austin Kids Events — powered by imagination.',
            connectTitle: 'How would you like to connect?',
            connectSubtitle: 'Choose your preferred channel below for fast answers, quick questions, or to see our latest party adventures!',
            connectWhatsApp: 'TEXT US ON WHATSAPP',
            connectCall: 'CALL US',
            connectLinktree: 'LINKTREE',
            connectInstagram: 'FOLLOW US ON INSTAGRAM',
            connectFacebook: 'FACEBOOK PAGE',
            connectWhatsAppText: 'Quick questions and party details',
            connectCallText: 'Direct calls for bookings',
            connectLinktreeText: 'See all our links in one place',
            connectInstagramText: 'Real setups, behind-the-scenes moments & play in action.',
            connectFacebookText: 'Community updates and events',
            exploreExperiences: 'EXPLORE THE EXPERIENCES',
            worldsTitle: 'Meet Our Play Worlds',
            filterAll: 'All Setups',
            filterRanch: 'Texas Ranch',
            filterSpace: 'Space Explorers',
            filterMiniSpace: 'Baby Space Explorers',
            filterCity: 'Mini City',
            worldLead: 'Choose a themed play setup designed for real play, big imaginations and memorable photos — delivered and professionally set up at your party venue.',
            worldRanchTag: 'THEME 01',
            worldSpaceTag: 'THEME 02',
            worldMiniTag: 'THEME 02B',
            worldCityTag: 'THEME 03',
            ranchTagline: 'A little piece of Texas made for big imaginations.',
            ranchCopy: 'Little cowboys and cowgirls can ride, roam and play their way through a hands-on ranch adventure with horses, tractors, farm animals and classic Texas details.',
            spaceTagline: 'A mission built for curious little astronauts.',
            spaceCopy: 'Rovers, space gear, lunar features and interactive activities turn the celebration into a hands-on mission where kids can explore, imagine and play beyond Earth.',
            miniTagline: 'A first little adventure beyond Earth.',
            miniCopy: 'Created for babies and toddlers up to 2½ years old, this softer lunar world combines sensory activities, space-themed play areas and age-appropriate exploration at their own pace.',
            cityTagline: 'A whole little city made for little drivers.',
            cityCopy: 'Mini City turns the party space into an interactive world of ride-on cars, roads and traffic signs where kids can drive, explore and create their own adventures. Along the way, they practice coordination, spatial awareness and imaginative play — while the colorful city display becomes part of the party décor and a natural backdrop for great photos.',
            ranchFeature1: 'Ranch Play',
            ranchFeature2: 'Horses',
            ranchFeature3: 'Farm Animals',
            ranchFeature4: 'Tractors',
            ranchFeature5: 'Barn',
            spaceFeature1: 'Space Rovers',
            spaceFeature2: 'Astronaut Gear',
            spaceFeature3: 'Lunar Command',
            spaceFeature4: 'Moon Terrain',
            spaceFeature5: 'Space Play',
            miniFeature1: 'Lunar Play Area',
            miniFeature2: 'Space Tents',
            miniFeature3: 'Sensory Play',
            miniFeature4: 'Activity Boards',
            miniFeature5: 'Little Explorers',
            cityFeature1: 'Ride-On Cars',
            cityFeature2: 'Roads',
            cityFeature3: 'Traffic Signs',
            cityFeature4: 'City Play',
            cityFeature5: 'Little Drivers',
            exploreRanch: 'Explore Texas Ranch',
            exploreSpace: 'Explore Space Explorers',
            exploreMini: 'Explore Baby Space Explorers',
            exploreCity: 'Explore Mini City',
            trustFooterTitle1: 'Serving Greater Austin',
            trustFooterText1: 'and surrounding areas. Professional delivery and setup included.',
            trustFooterTitle2: 'Clean, Safe & Inspected',
            trustFooterText2: 'Our equipment is sanitized and safety-checked before every event.',
            trustFooterTitle3: '12-Hour Rental',
            trustFooterText3: 'Plenty of time to enjoy! Typically delivered before 10 AM and picked up after 9 PM.',
            trustFooterTitle4: 'Made for Memories',
            trustFooterText4: 'Designed for real play, beautiful photos and hassle-free celebrations.',
            viewSetup: 'Explore setup',
            viewAllSetups: '← View all setups',
            detailSet: 'Interactive party setup',
            detailExperience: 'The experience',
            detailMission: 'The mission briefing',
            detailBook: 'I want this set',
            detailReserve: 'Book this mission',
            detailBuild: 'Build their city',
            spaceAgeSuffix: 'years',
            miniAgeSuffix: 'years',
            spaceCommandLabel: 'Mission control',
            spaceReady: 'READY FOR TAKEOFF',
            spaceSpecWindow: 'Rental window',
            spaceSpecZone: 'Launch zone',
            spaceSignoff: 'Once the helmets go on, somebody usually starts assigning missions.',
            cityStoryTitle: 'A little world with no wrong turn.',
            cityChoiceText: 'Families can choose between different Mini City configurations, from colorful classic ride-on vehicles to a more polished collection of luxury-style cars.',
            cityDeliveryText: 'Each setup is delivered and fully arranged before your event, then picked up afterward. Rentals are available for up to 12 hours, and selected activity or entertainment add-ons can be included depending on the celebration.',
            cityAvailabilityText: 'Available for birthdays, family gatherings and children’s events throughout the Greater Austin area.',
            cityControlLabel: 'City control',
            cityStatus: 'ALL ROUTES OPEN',
            citySpecWindow: 'Rental window',
            citySpecZone: 'Play zone',
            citySignoff: 'And unlike I-35, traffic in Mini City is actually part of the fun! 😄',
            miniCommandLabel: 'Mission control',
            miniReady: 'READY FOR LITTLE EXPLORERS',
            miniSpecWindow: 'Rental window',
            miniSpecZone: 'Play zone',
            miniSpecSignoff: 'Small explorers, big discoveries.',
            ranchBack: '← View all setups',
            ranchKicker: 'Interactive party setup',
            ranchLead: 'A countryside adventure where kids can play, explore and enjoy a celebration with plenty of personality.',
            ranchCta: 'I want this set',
            ranchInfoTitle: 'THE PLAY SETUP',
            ranchInfoText: 'A Little Ranch for Big Imaginations',
            ranchBodyIntro: 'Saddle up for hands-on play with ride-on horses, child-sized tractors, a mini corral with cows, artificial turf, white fencing, and playful ranch-themed details. We deliver and professionally set up everything at your venue, ready for little ranchers to play and explore.',
            ranchIncludesLabel: 'Includes',
            ranchIncludesText: 'Ride-on horses, tractors & mini corral',
            ranchIdealLabel: 'Ideal for',
            ranchIdealText: 'Kids’ parties',
            ranchThemeLabel: 'Theme',
            ranchThemeText: 'Texas Ranch',
            bringIt: 'BRING IT TO',
            toMyParty: 'MY PARTY &rarr;',
            spaceBack: '← View all setups',
            spaceKicker: 'Interactive party setup',
            spaceLead: 'Little Astronauts. Big Missions.',
            spaceCta: 'Book this mission',
            spaceMissionKicker: 'THE MISSION',
            spaceMissionTitle: 'Little Astronauts. Big Missions.',
            spaceMissionText1: 'Space Explorers is designed for children ages 3 to 5 who are ready to drive, explore, and invent their own adventures. Little astronauts can cross the lunar surface, report to the Space Command Center, and create new missions while playing together.',
            spaceMissionText2: '',
            spaceMissionText3: '',
            spaceMissionText4: '',
            spaceSpecAge: 'Recommended ages',
            spaceSpecWindow: 'Rental period',
            spaceSpecZone: 'Service',
            spaceSpecAvailable: 'Available in',
            spaceSpecAgeValue: '3 to 5 years',
            spaceSpecWindowValue: 'Up to 12 hours',
            spaceSpecZoneValue: 'Delivery, professional setup, and pickup',
            spaceSpecAvailableValue: 'Austin, Round Rock, Pflugerville, Georgetown, Cedar Park, and Leander',
            spaceCommandLabel: 'Mission control',
            spaceReady: 'READY FOR TAKEOFF',
            spaceSignoff: 'Once the helmets go on, somebody usually starts assigning missions.',
            cityBack: '← View all setups',
            cityKicker: 'Open-ended play setup',
            cityLead: 'A whole little city made for little drivers.',
            cityCta: 'BRING IT TO',
            toMyParty: 'MY PARTY →',
            cityInfoTitle: 'Mini City',
            cityInfoText: 'Mini City turns the party space into an interactive world of ride-on cars, roads and traffic signs where kids can drive, explore and create their own adventures. Along the way, they practice coordination, spatial awareness and imaginative play — while the colorful city display becomes part of the party décor and a natural backdrop for great photos.',
            miniBack: '← View all setups',
            miniKicker: 'SENSORY PLAY AREA · AGES 0–2½',
            miniLead: 'A little lunar adventure designed for our youngest explorers — babies and toddlers up to 2½ years old.',
            miniCta: 'Book this adventure',
            miniMissionKicker: 'THE MISSION',
            miniMissionTitle: 'The first mission begins on the Moon.',
            miniMissionText1: 'Baby Space Explorers turns the celebration into a cozy lunar corner for babies and toddlers up to 2 years and 6 months old. There they can crawl, move, touch, and discover at their own rhythm.',
            miniMissionText2: 'The space modules, activity panels, and sensory elements invite them to follow their curiosity and find something new with every movement. We bring, set up, and remove the full play area so everything is ready before the mission begins.',
            miniSpecAge: 'Age range',
            miniSpecWindow: 'Rental window',
            miniSpecZone: 'Play zone',
            miniSpecUpTo: 'Ages 0–2½',
            miniSpecHours: 'Up to 12 hours',
            miniSpecAustin: 'Greater Austin',
            miniSpecSignoff: 'Small explorers, big discoveries.',
            miniBringIt: 'BRING THE MOON TO MY PARTY →',
            miniToMyParty: 'MY PARTY →'
        }
    };

    const getStoredLang = () => {
        try {
            const value = localStorage.getItem('austinKidsLang');
            return value === 'en' || value === 'es' ? value : 'es';
        } catch (error) {
            return 'es';
        }
    };

    const applyTranslations = (lang) => {
        const map = translations[lang] || translations.es;
        document.documentElement.lang = lang;
        document.body.dataset.lang = lang;

        document.querySelectorAll('[data-i18n]').forEach((element) => {
            const key = element.dataset.i18n;
            if (map[key]) {
                if (key === 'successLead') {
                    element.innerHTML = map[key];
                } else {
                    element.textContent = map[key];
                }
            }
        });

        document.querySelectorAll('.lang-option').forEach((button) => {
            const isActive = button.dataset.lang === lang;
            button.classList.toggle('is-active', isActive);
            button.setAttribute('aria-pressed', String(isActive));
        });
    };

    document.addEventListener('click', (event) => {
        const button = event.target.closest('.lang-option');
        if (!button) return;

        const lang = button.dataset.lang;
        if (!lang) return;

        try {
            localStorage.setItem('austinKidsLang', lang);
        } catch (error) {
            // No-op: storage unavailable in some browsers.
        }

        applyTranslations(lang);
    });

    applyTranslations(getStoredLang());
})();
