(function () {
    const translations = {
        es: {
            heroTitle: 'BIG IMAGINATIONS. LITTLE ADVENTURES.',
            heroSubtitle: 'Alquileres de fiestas infantiles temáticas y sets de juego interactivos en Greater Austin.',
            heroDescription: 'Llevamos juego imaginativo a tu celebración con vehículos temáticos, actividades sensoriales y experiencias interactivas — entregadas y montadas profesionalmente en tu evento.',
            servicesBtn: 'Ver servicios',
            contactBtn: 'Contáctanos',
            homeBtn: 'Inicio',
            backHome: '← Volver al inicio',
            servicesTitle: 'Alquileres de vehículos infantiles temáticos',
            servicesDesc: 'Elige un vehículo temático y conviértete en una fiesta inolvidable.',
            ranchCardTitle: 'Alquiler de vehículo Texas Ranch',
            spaceCardTitle: 'Alquiler de vehículo Space Explorers',
            miniSpaceCardTitle: 'Baby Space Explorers',
            cityCardTitle: 'Alquiler de vehículo Mini City',
            bringIt: 'Llévame',
            toMyParty: 'A Mi Fiesta',
            contactBackHome: '← Volver al inicio',
            directoryTab: 'Directorio y historia',
            quoteTab: 'Solicitar cotización',
            contactTitle: 'Planifiquemos su gran día',
            contactIntro: 'Cuéntanos sobre tu celebración y te ayudaremos a elegir el setup perfecto.',
            formFirstName: 'Nombre',
            formLastName: 'Apellido',
            formPhone: 'Número de teléfono',
            formEmail: 'Correo electrónico',
            formZip: 'Código postal del evento',
            formDate: 'Fecha del evento',
            formDateHelp: 'Elige una fecha del calendario.',
            locationLegend: '¿Dónde será la celebración?',
            locationHome: 'Casa privada',
            locationPark: 'Parque',
            locationVenue: 'Lugar / salón',
            setupPrompt: '¿Qué setup te gustaría cotizar?',
            setupDefault: 'Selecciona un setup',
            requestQuote: 'Solicitar cotización',
            successTitle: '¡Solicitud recibida!',
            successLead: 'Gracias, <strong id="successCustomerName">amigo</strong>! Hemos recibido los detalles de tu celebración.',
            successSetup: 'Setup:',
            successDate: 'Fecha:',
            successLocation: 'Ubicación:',
            whatsappBtn: '💬 Escríbenos por WhatsApp',
            sendAnother: 'Enviar otra solicitud',
            directoryBackHome: '← Volver al inicio',
            directoryStoryTitle: '¡Gracias por pasar por aquí! ✨',
            directoryStoryIntro: 'Sabemos que planear una celebración toma tiempo, amor y atención a cada detalle. Estamos muy contentos y agradecidos de que estés aquí explorando nuestro universo lúdico.',
            trustAustin: '📍 Sirviendo a Greater Austin y áreas cercanas',
            trustClean: '🧼 100% limpiado y desinfectado',
            trustSetup: '🚚 Entregado y montado profesionalmente',
            storyMission: 'NUESTRA HISTORIA Y MISIÓN',
            storyHeadline: 'Algunos momentos llevan años soñándose — y solo unas horas viviéndose.',
            storyIntro1: 'Esa idea siempre ha estado en el corazón de Austin Kids Events. Sabemos lo mucho que puede implicar un primer cumpleaños: la anticipación, la planificación, los pequeños detalles y la esperanza de que, cuando llegue el día, se sienta realmente especial.',
            storyIntro2: 'Por eso quisimos crear algo que haga más que llenar un espacio de fiesta. Nuestros setups están diseñados para que los niños realmente jueguen, exploren e imaginen, mientras también se convierten en parte de la celebración, creando fotos hermosas y dando a los padres menos cosas que gestionar.',
            storyIntro3: 'Porque cuando empieza la fiesta, también deberías poder disfrutarla.',
            storyQuote: 'La infancia pasa rápido. Estamos aquí para hacer que algunos momentos valgan la pena recordar.',
            storyTagline: 'Austin Kids Events — impulsado por la imaginación.',
            connectTitle: '¿Cómo te gustaría conectar?',
            connectSubtitle: 'Elige tu canal preferido para respuestas rápidas, preguntas rápidas o para ver nuestras últimas aventuras de fiesta.',
            connectWhatsApp: 'MÉNSAJE POR WHATSAPP',
            connectCall: 'LLÁMANOS',
            connectLinktree: 'LINKTREE',
            connectInstagram: 'SIGUE INSTAGRAM',
            connectFacebook: 'PÁGINA DE FACEBOOK',
            connectWhatsAppText: 'Preguntas rápidas y detalles de la fiesta',
            connectCallText: 'Llamadas directas para reservaciones',
            connectLinktreeText: 'Mira todos nuestros enlaces en un solo lugar',
            connectInstagramText: 'Fotos, videos en vivo e inspiración para fiestas',
            connectFacebookText: 'Actualizaciones y eventos de la comunidad',
            exploreExperiences: 'EXPLORA LAS EXPERIENCIAS',
            worldsTitle: 'Conoce nuestros mundos de juego',
            filterAll: 'Todos los setups',
            filterRanch: 'Texas Ranch',
            filterSpace: 'Space Explorers',
            filterMiniSpace: 'Baby Space Explorers',
            filterCity: 'Mini City',
            worldLead: 'Elige un setup temático pensado para jugar de verdad, imaginar en grande y crear fotos memorables — entregado y montado profesionalmente en tu evento.',
            worldRanchTag: 'TEMA 01',
            worldSpaceTag: 'TEMA 02',
            worldMiniTag: 'TEMA 02B',
            worldCityTag: 'TEMA 03',
            ranchTagline: 'Un pedacito de Texas hecho para grandes imaginaciones.',
            ranchCopy: 'Los vaqueros y vaqueras pequeños pueden montar, recorrer y jugar su camino a través de una aventura de rancho con caballos, tractores, animales de granja y detalles clásicos de Texas.',
            spaceTagline: 'Una misión pensada para pequeños astronautas curiosos.',
            spaceCopy: 'Los rovers, el equipo espacial, los paisajes lunares y las actividades interactivas convierten la celebración en una misión práctica donde los niños pueden explorar, imaginar y jugar más allá de la Tierra.',
            miniTagline: 'Una primera aventura pequeña más allá de la Tierra.',
            miniCopy: 'Diseñado para bebés y toddlers hasta 2½ años, este mundo lunar más suave combina actividades sensoriales, áreas de juego con temática espacial y exploración apropiada para su edad a su propio ritmo.',
            cityTagline: 'Toda una ciudad pequeña hecha para pequeños conductores.',
            cityCopy: 'Autos a pedal, calles, señales de tráfico y juego imaginativo dan a los niños su propio mundo para conducir, explorar y crear sus propias reglas mientras avanza el juego.',
            ranchFeature1: 'Juegos de rancho',
            ranchFeature2: 'Caballos',
            ranchFeature3: 'Animales de granja',
            ranchFeature4: 'Tractores',
            ranchFeature5: 'Granero',
            spaceFeature1: 'Rovers espaciales',
            spaceFeature2: 'Equipo de astronauta',
            spaceFeature3: 'Mando lunar',
            spaceFeature4: 'Terreno lunar',
            spaceFeature5: 'Juego espacial',
            miniFeature1: 'Área de juego lunar',
            miniFeature2: 'Carpas espaciales',
            miniFeature3: 'Juego sensorial',
            miniFeature4: 'Tableros de actividad',
            miniFeature5: 'Pequeños exploradores',
            cityFeature1: 'Autos a pedal',
            cityFeature2: 'Calles',
            cityFeature3: 'Señales de tráfico',
            cityFeature4: 'Juego de ciudad',
            cityFeature5: 'Pequeños conductores',
            exploreRanch: 'Explorar Texas Ranch',
            exploreSpace: 'Explorar Space Explorers',
            exploreMini: 'Explorar Baby Space Explorers',
            exploreCity: 'Explorar Mini City',
            trustFooterTitle1: 'Atendemos Greater Austin',
            trustFooterText1: 'y áreas cercanas. Entrega y montaje profesional incluidos.',
            trustFooterTitle2: 'Limpio, seguro y revisado',
            trustFooterText2: 'Nuestro equipo se limpia y revisa antes de cada evento.',
            trustFooterTitle3: 'Renta de 12 horas',
            trustFooterText3: 'Hay tiempo de sobra para disfrutar. Normalmente se entrega antes de las 10 AM y se recoge después de las 9 PM.',
            trustFooterTitle4: 'Hecho para recuerdos',
            trustFooterText4: 'Diseñado para jugar de verdad, fotos bonitas y celebraciones sin estrés.',
            viewSetup: 'Explorar setup',
            viewAllSetups: '← Ver todos los setups',
            detailSet: 'Set de juegos',
            detailExperience: 'La experiencia',
            detailMission: 'La misión',
            detailBook: 'Quiero este set',
            detailReserve: 'Reservar esta aventura',
            detailBuild: 'Construyan su ciudad',
            spaceAgeSuffix: 'años',
            miniAgeSuffix: 'años',
            spaceCommandLabel: 'Centro de mando',
            spaceReady: 'LISTOS PARA DESPEGAR',
            spaceSpecStart: 'Precio desde',
            spaceSpecWindow: 'Horario de alquiler',
            spaceSpecZone: 'Zona de lanzamiento',
            spaceSignoff: 'Cuando se ponen los cascos, alguien suele empezar a asignar misiones.',
            cityStoryTitle: 'Un pequeño mundo sin equivocación.',
            cityChoiceText: 'Las familias pueden elegir entre distintas configuraciones de Mini City, desde vehículos clásicos a pedal hasta una colección más elegante de autos estilo lujo.',
            cityDeliveryText: 'Cada setup se entrega y se monta completamente antes del evento, y se recoge después. Los alquileres duran hasta 12 horas, y se pueden incluir actividades o entretenimiento adicional dependiendo de la celebración.',
            cityAvailabilityText: 'Disponible para cumpleaños, reuniones familiares y eventos infantiles en todo Greater Austin.',
            cityControlLabel: 'Control de la ciudad',
            cityStatus: 'TODAS LAS RUTAS ABIERTAS',
            citySpecStart: 'Precio desde',
            citySpecWindow: 'Horario de alquiler',
            citySpecZone: 'Zona de juego',
            citySignoff: 'Y a diferencia del I-35, el tráfico en Mini City es parte de la diversión. 😄',
            miniCommandLabel: 'Centro de mando',
            miniReady: 'LISTOS PARA EXPLORADORES PEQUEÑOS',
            miniSpecStart: 'Precio desde',
            miniSpecWindow: 'Horario de alquiler',
            miniSpecZone: 'Zona de juego',
            miniSpecSignoff: 'Pequeños exploradores, grandes descubrimientos.',
            ranchBack: '← Ver todos los setups',
            ranchKicker: 'Set de juegos',
            ranchLead: 'Una aventura campirana para que los pequeños jueguen, exploren y disfruten una fiesta con mucha personalidad.',
            ranchCta: 'Quiero este set',
            ranchInfoTitle: 'Diversión con sabor a rancho',
            ranchInfoText: 'Cerco perimetral, animales inflables, alfombra de césped artificial y decoración temática campirana para transformar tu evento en un pequeño rancho.',
            ranchSpecPrice: 'Precio desde',
            ranchSpecIdeal: 'Ideal para',
            ranchSpecTheme: 'Temática',
            spaceBack: '← Ver todos los setups',
            spaceKicker: 'Set de juegos interactivo',
            spaceLead: 'Space Explorers convierte parte de tu celebración en una pequeña zona de misión donde los niños pueden subir a bordo, equiparse y decidir hacia dónde va la expedición.',
            spaceCta: 'Reservar esta misión',
            spaceMissionKicker: 'La misión',
            spaceMissionTitle: 'Un pequeño universo pensado para grandes imaginaciones.',
            spaceMissionText1: 'El setup incluye cuatro rover espaciales, cascos de astronauta, un Centro de Mando Espacial, paisaje lunar y elementos de equilibrio, todo organizado para crear un entorno interactivo en lugar de una colección de juguetes separados.',
            spaceMissionText2: 'Diseñado especialmente para edades 3-5, los niños pueden conducir sus rovers, reportar al mando, cruzar la “superficie lunar” y crear sus propias misiones mientras la fiesta avanza.',
            spaceMissionText3: 'El setup completo se entrega y se instala antes del evento y luego se recoge después. Los alquileres tienen una duración de hasta 12 horas, con actividades y entretenimiento adicional disponible dependiendo de la celebración.',
            spaceMissionText4: 'Disponible para cumpleaños y eventos infantiles en todo Greater Austin.',
            cityBack: '← Ver todos los setups',
            cityKicker: 'Setup de juego abierto',
            cityLead: 'Mini City da a los niños su propio pequeño mundo para recorrer, explorar y convertir en la historia que quieran crear.',
            cityCta: 'Construyan su ciudad',
            cityInfoTitle: 'La historia de la ciudad',
            cityInfoText: 'La ciudad en miniatura combina autos a pedal, caminos, señales de tráfico y elementos de juego imaginativos en un único espacio organizado para jugar de forma activa y abierta.',
            miniBack: '← Ver todos los setups',
            miniKicker: 'Exploradores del espacio para los más pequeños',
            miniLead: 'Una aventura lunar pequeña, diseñada para nuestras exploradoras y exploradores más pequeños — bebés y toddlers hasta 2½ años.',
            miniCta: 'Reservar esta aventura',
            miniMissionKicker: 'La misión',
            miniMissionTitle: 'Un espacio lunar lleno de juego para exploradores tempranos.',
            miniMissionText1: 'Baby Space Explorers crea un espacio lunar lleno de juego donde los más pequeños pueden gatear, explorar y descubrir a su propio ritmo.',
            miniMissionText2: 'El setup combina un área lunar suave, carpas temáticas espaciales y actividades interactivas apropiadas para su edad que fomentan el juego sensorial, la curiosidad y la exploración temprana — todo entregado y montado profesionalmente para tu celebración.',
            miniSpecAge: 'Rango de edad',
            miniSpecWindow: 'Horario de alquiler',
            miniSpecZone: 'Zona de juego',
            miniSpecUpTo: 'Hasta 2½ años',
            miniSpecHours: 'Hasta 12 horas',
            miniSpecAustin: 'Greater Austin',
            miniSpecSignoff: 'Pequeños exploradores, grandes descubrimientos.'
        },
        en: {
            heroTitle: 'BIG IMAGINATIONS. LITTLE ADVENTURES.',
            heroSubtitle: 'Themed kids party rentals and interactive play setups in Greater Austin.',
            heroDescription: 'We bring imaginative play to your celebration with themed ride-ons, sensory activities and interactive experiences — delivered and professionally set up at your party venue.',
            servicesBtn: 'View services',
            contactBtn: 'Contact us',
            homeBtn: 'Home',
            backHome: '← Back to home',
            servicesTitle: 'Themed Kids Vehicle Rentals',
            servicesDesc: 'Choose a themed vehicle setup and turn your party into an unforgettable event.',
            ranchCardTitle: 'Texas Ranch Vehicle Rental',
            spaceCardTitle: 'Space Explorers Vehicle Rental',
            miniSpaceCardTitle: 'Baby Space Explorers',
            cityCardTitle: 'Mini City Vehicle Rental',
            bringIt: 'Bring It',
            toMyParty: 'To My Party',
            contactBackHome: '← Back to home',
            directoryTab: 'Directory & Story',
            quoteTab: 'Request a Quote',
            contactTitle: 'Let’s plan their big day',
            contactIntro: 'Tell us about your celebration and we’ll help you choose the perfect setup.',
            formFirstName: 'First name',
            formLastName: 'Last name',
            formPhone: 'Phone number',
            formEmail: 'Email address',
            formZip: 'Event ZIP code',
            formDate: 'Event date',
            formDateHelp: 'Choose a date from the calendar.',
            locationLegend: 'Where will the celebration take place?',
            locationHome: 'Private home',
            locationPark: 'Park',
            locationVenue: 'Venue / Hall',
            setupPrompt: 'Which setup would you like a quote for?',
            setupDefault: 'Select a setup',
            requestQuote: 'Request a quote',
            successTitle: 'Request Received!',
            successLead: 'Thank you, <strong id="successCustomerName">there</strong>! We’ve received your celebration details.',
            successSetup: 'Setup:',
            successDate: 'Date:',
            successLocation: 'Location:',
            whatsappBtn: '💬 Message us on WhatsApp',
            sendAnother: 'Send another request',
            directoryBackHome: '← Back to home',
            directoryStoryTitle: 'Thank you for stopping by! ✨',
            directoryStoryIntro: 'We know planning a celebration takes time, love, and attention to every detail. We are so happy and grateful you are here exploring our playful universe!',
            trustAustin: '📍 Serving Greater Austin & Surrounding Areas',
            trustClean: '🧼 100% Cleaned & Sanitized',
            trustSetup: '🚚 Delivered & Professionally Setup',
            storyMission: 'OUR STORY & MISSION',
            storyHeadline: 'Some moments take years to dream about — and only a few hours to live.',
            storyIntro1: 'That idea has always been at the heart of Austin Kids Events. We know how much can go into those first birthdays: the anticipation, the planning, the little details, and the hope that when the day finally comes, it feels truly special.',
            storyIntro2: 'So we wanted to create something that does more than fill a party space. Our setups are made for kids to actually play, explore and imagine — while also becoming part of the celebration itself, creating beautiful photos and giving parents fewer things to manage.',
            storyIntro3: 'Because when the party starts, you should be able to enjoy it too.',
            storyQuote: 'Childhood goes by fast. We’re here to make some of it worth remembering.',
            storyTagline: 'Austin Kids Events — powered by imagination.',
            connectTitle: 'How would you like to connect?',
            connectSubtitle: 'Choose your preferred channel below for fast answers, quick questions, or to see our latest party adventures!',
            connectWhatsApp: 'TEXT US ON WHATSAPP',
            connectCall: 'CALL US',
            connectLinktree: 'LINKTREE',
            connectInstagram: 'FOLLOW INSTAGRAM',
            connectFacebook: 'FACEBOOK PAGE',
            connectWhatsAppText: 'Quick questions and party details',
            connectCallText: 'Direct calls for bookings',
            connectLinktreeText: 'See all our links in one place',
            connectInstagramText: 'Photos, live videos & party inspiration',
            connectFacebookText: 'Community updates and events',
            exploreExperiences: 'EXPLORE THE EXPERIENCES',
            worldsTitle: 'Meet Our Play Worlds',
            filterAll: 'All Setups',
            filterRanch: 'Texas Ranch',
            filterSpace: 'Space Explorers',
            filterMiniSpace: 'Baby Space Explorers',
            filterCity: 'Mini City',
            worldLead: 'Choose a themed play setup designed for real play, big imaginations and memorable photos — delivered and professionally set up at your party venue.',
            worldRanchTag: 'THEME 01',
            worldSpaceTag: 'THEME 02',
            worldMiniTag: 'THEME 02B',
            worldCityTag: 'THEME 03',
            ranchTagline: 'A little piece of Texas made for big imaginations.',
            ranchCopy: 'Little cowboys and cowgirls can ride, roam and play their way through a hands-on ranch adventure with horses, tractors, farm animals and classic Texas details.',
            spaceTagline: 'A mission built for curious little astronauts.',
            spaceCopy: 'Rovers, space gear, lunar features and interactive activities turn the celebration into a hands-on mission where kids can explore, imagine and play beyond Earth.',
            miniTagline: 'A first little adventure beyond Earth.',
            miniCopy: 'Created for babies and toddlers up to 2½ years old, this softer lunar world combines sensory activities, space-themed play areas and age-appropriate exploration at their own pace.',
            cityTagline: 'A whole little city made for little drivers.',
            cityCopy: 'Ride-on cars, roads, traffic signs and imaginative city play give kids their own world to drive, explore and make up the rules as they go.',
            ranchFeature1: 'Ranch Play',
            ranchFeature2: 'Horses',
            ranchFeature3: 'Farm Animals',
            ranchFeature4: 'Tractors',
            ranchFeature5: 'Barn',
            spaceFeature1: 'Space Rovers',
            spaceFeature2: 'Astronaut Gear',
            spaceFeature3: 'Lunar Command',
            spaceFeature4: 'Moon Terrain',
            spaceFeature5: 'Space Play',
            miniFeature1: 'Lunar Play Area',
            miniFeature2: 'Space Tents',
            miniFeature3: 'Sensory Play',
            miniFeature4: 'Activity Boards',
            miniFeature5: 'Little Explorers',
            cityFeature1: 'Ride-On Cars',
            cityFeature2: 'Roads',
            cityFeature3: 'Traffic Signs',
            cityFeature4: 'City Play',
            cityFeature5: 'Little Drivers',
            exploreRanch: 'Explore Texas Ranch',
            exploreSpace: 'Explore Space Explorers',
            exploreMini: 'Explore Baby Space Explorers',
            exploreCity: 'Explore Mini City',
            trustFooterTitle1: 'Serving Greater Austin',
            trustFooterText1: 'and surrounding areas. Professional delivery and setup included.',
            trustFooterTitle2: 'Clean, Safe & Inspected',
            trustFooterText2: 'Our equipment is sanitized and safety-checked before every event.',
            trustFooterTitle3: '12-Hour Rental',
            trustFooterText3: 'Plenty of time to enjoy! Typically delivered before 10 AM and picked up after 9 PM.',
            trustFooterTitle4: 'Made for Memories',
            trustFooterText4: 'Designed for real play, beautiful photos and hassle-free celebrations.',
            viewSetup: 'Explore setup',
            viewAllSetups: '← View all setups',
            detailSet: 'Interactive party setup',
            detailExperience: 'The experience',
            detailMission: 'The mission briefing',
            detailBook: 'I want this set',
            detailReserve: 'Book this mission',
            detailBuild: 'Build their city',
            spaceAgeSuffix: 'years',
            miniAgeSuffix: 'years',
            spaceCommandLabel: 'Mission control',
            spaceReady: 'READY FOR TAKEOFF',
            spaceSpecStart: 'Starting at',
            spaceSpecWindow: 'Rental window',
            spaceSpecZone: 'Launch zone',
            spaceSignoff: 'Once the helmets go on, somebody usually starts assigning missions.',
            cityStoryTitle: 'A little world with no wrong turn.',
            cityChoiceText: 'Families can choose between different Mini City configurations, from colorful classic ride-on vehicles to a more polished collection of luxury-style cars.',
            cityDeliveryText: 'Each setup is delivered and fully arranged before your event, then picked up afterward. Rentals are available for up to 12 hours, and selected activity or entertainment add-ons can be included depending on the celebration.',
            cityAvailabilityText: 'Available for birthdays, family gatherings and children’s events throughout the Greater Austin area.',
            cityControlLabel: 'City control',
            cityStatus: 'ALL ROUTES OPEN',
            citySpecStart: 'Starting at',
            citySpecWindow: 'Rental window',
            citySpecZone: 'Play zone',
            citySignoff: 'And unlike I-35, traffic in Mini City is actually part of the fun! 😄',
            miniCommandLabel: 'Mission control',
            miniReady: 'READY FOR LITTLE EXPLORERS',
            miniSpecStart: 'Starting at',
            miniSpecWindow: 'Rental window',
            miniSpecZone: 'Play zone',
            miniSpecSignoff: 'Small explorers, big discoveries.',
            ranchBack: '← View all setups',
            ranchKicker: 'Interactive party setup',
            ranchLead: 'A countryside adventure where kids can play, explore and enjoy a celebration with plenty of personality.',
            ranchCta: 'I want this set',
            ranchInfoTitle: 'Fun with a ranch flavor',
            ranchInfoText: 'Perimeter fence, inflatable animals, artificial grass, and ranch-themed décor to transform your event into a little ranch.',
            ranchSpecPrice: 'Starting at',
            ranchSpecIdeal: 'Ideal for',
            ranchSpecTheme: 'Theme',
            spaceBack: '← View all setups',
            spaceKicker: 'Interactive party setup',
            spaceLead: 'Space Explorers turns part of your celebration into a small mission area where kids can climb aboard, gear up and decide where the expedition goes next.',
            spaceCta: 'Book this mission',
            spaceMissionKicker: 'The mission briefing',
            spaceMissionTitle: 'A little universe built for big imaginations.',
            spaceMissionText1: 'The setup includes four kid-powered space rovers, astronaut helmets, a Space Command Center, moon-inspired scenery and balance-play elements, all arranged together to create one interactive environment rather than a collection of separate toys.',
            spaceMissionText2: 'Designed especially for ages 3-5, children can drive their rovers, report back to command, cross the “lunar surface” and create their own missions as the party unfolds.',
            spaceMissionText3: 'The complete setup is delivered and arranged before your event, then picked up afterward. Rentals are available for up to 12 hours, with selected activity and entertainment add-ons available depending on your celebration.',
            spaceMissionText4: 'Available for birthdays and children’s events throughout the Greater Austin area.',
            cityBack: '← View all setups',
            cityKicker: 'Open-ended play setup',
            cityLead: 'Mini City gives young children their own little world to drive through, explore and turn into whatever story they want to create.',
            cityCta: 'Build their city',
            cityInfoTitle: 'The city story',
            cityInfoText: 'Mini City combines ride-on cars, roads, traffic signs and playful city features in one organized space designed for active, open-ended play.',
            miniBack: '← View all setups',
            miniKicker: 'Space explorers for little ones',
            miniLead: 'A little lunar adventure designed for our youngest explorers — babies and toddlers up to 2½ years old.',
            miniCta: 'Book this adventure',
            miniMissionKicker: 'The mission briefing',
            miniMissionTitle: 'A playful moon-inspired space for early explorers.',
            miniMissionText1: 'Baby Space Explorers creates a playful moon-inspired space where little ones can crawl, explore and discover at their own pace.',
            miniMissionText2: 'The setup combines a soft lunar play area, space-themed tents and age-appropriate interactive activities that encourage sensory play, curiosity and early exploration — all professionally delivered and set up for your celebration.',
            miniSpecAge: 'Age range',
            miniSpecWindow: 'Rental window',
            miniSpecZone: 'Play zone',
            miniSpecUpTo: 'Up to 2½ years',
            miniSpecHours: 'Up to 12 hours',
            miniSpecAustin: 'Greater Austin',
            miniSpecSignoff: 'Small explorers, big discoveries.'
        }
    };

    const getStoredLang = () => {
        try {
            const value = localStorage.getItem('austinKidsLang');
            return value === 'en' || value === 'es' ? value : 'es';
        } catch (error) {
            return 'es';
        }
    };

    const applyTranslations = (lang) => {
        const map = translations[lang] || translations.es;
        document.documentElement.lang = lang;
        document.body.dataset.lang = lang;

        document.querySelectorAll('[data-i18n]').forEach((element) => {
            const key = element.dataset.i18n;
            if (map[key]) {
                element.textContent = map[key];
            }
        });

        document.querySelectorAll('.lang-option').forEach((button) => {
            const isActive = button.dataset.lang === lang;
            button.classList.toggle('is-active', isActive);
            button.setAttribute('aria-pressed', String(isActive));
        });
    };

    document.addEventListener('click', (event) => {
        const button = event.target.closest('.lang-option');
        if (!button) return;

        const lang = button.dataset.lang;
        if (!lang) return;

        try {
            localStorage.setItem('austinKidsLang', lang);
        } catch (error) {
            // No-op: storage unavailable in some browsers.
        }

        applyTranslations(lang);
    });

    applyTranslations(getStoredLang());
})();
